### ISSUE TITLE
Render PDF Files

### ISSUE THREAD

**Issue by jokulab** [ndy2/mkdocs-obsidian-support-plugin#3]
Hi, 

I wanted to ask if it would be possible to also render the pdfs tat can be rendered in Obsidian (with `![[test.pdf]]`).
This probably could be achieved with a `iframe` or something else.

I  hope this is possible to implement, because there is literally no other plugin out there that can do this.

Regards

**Comment by ndy2** [comment]
Thank you for your suggestion.

**markdown**
```
![[sample.pdf]]
```

**rendered**
- infer width & height using `pypdf`
```
<iframe src="sample.pdf" width="700" height="940"> </iframe>
```

I would try on above sterategy.
But i'm a bit busy these days, so I think it will take up to 2 weeks.

**Comment by ndy2** [comment]
Sorry for late reply. I tried this. But with my bad frontend knoledge, i was not able to make responsive and cool looking ui for embedded pdf. Also there should be some another libary like `pypdf` to get the width and height of the given pdf which is over the range of this plugin. 

This plugin should provide simple regex based syntax transport, not dynamic resolution for some contnent.
If you requires the dynamic conversion like this, I suggest mkdocs-macro as a solution for it.

Somehow i would remain this issue as open.
Someone who can implement this feature without other dependencies and only with some extra css and html conversion,  please help with this issue

**Comment by ndy2** [comment]
@jokulab !
I add requested feature in new release. It was quite late. Again, Sorry for late reply.
You can see https://ndy2.github.io/mkdocs-obsidian-support-plugin/features/pdf/ to see the usage with examples
