### ISSUE TITLE
Missing import override

### ISSUE THREAD

**Issue by SebastianErfort** [ndy2/mkdocs-obsidian-support-plugin#41]
Hi there,

in 6586243a you introduced

```python
from overrides import override
# and
from overrides import final
```

These imports give me errors as I don't have the module(s) to be loaded.

Can you please tell me where to find it or make it part of the package?

Thank you and cheers, Sebastian

**Comment by ndy2** [comment]
Hi.

It's in [requirements.txt](https://github.com/ndy2/mkdocs-obsidian-support-plugin/blob/13e724f5e43df4d66e330dc464711a05b407d7f3/requirements.txt#L6).
And it is https://github.com/mkorpela/overrides <- this libary.

It simply checks the overrided method has correct signature from its parent in when its loaded.

You can install it by `pip install overrides` or install or requriements by `pip install -r requirements.txt` .

**Comment by SebastianErfort** [comment]
That wasn't so hard to find :man_facepalming: Thank you

**Comment by ndy2** [comment]
However, sorry for bad commit history. 😅
