### ISSUE TITLE
overrides dependency of the package is missing

### ISSUE THREAD

**Issue by daxcore** [ndy2/mkdocs-obsidian-support-plugin#44]
https://github.com/ndy2/mkdocs-obsidian-support-plugin/blob/53a85aaecdef5ac122bde6657b147a1e3a4e7bb2/setup.py#L24

IMO u should add `overrides~=7.7.0` also in package.

**Comment by ndy2** [comment]
Thank you for suggestion. I applied it.
Somehow, #41 might be due to this missing dependency in setup.py.
